JeuxCritique/WebApplication1/Controllers/criticsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1;

namespace WebApplication1.Controllers
{
    [Authorize]
    public class criticsController : Controller
    {
        private JCModelEntities db = new JCModelEntities();

        // GET: critics
        [AllowAnonymous]
        public ActionResult Index()
        {
            var critics = db.critics.Include(c => c.games);
            return View(critics.ToList());
        }

        // GET: critics/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            critics critics = db.critics.Find(id);
            //comments comments = db.comments.Where(g => g.id_critic == id);
            if (critics == null)
            {
                return HttpNotFound();
            }
            return View(critics);
        }

        // GET: critics/Create
        public ActionResult Create()
        {
            ViewBag.category_id = new SelectList(db.category, "id_category", "category_name");
            ViewBag.game_id = new SelectList(db.games, "game_id", "name");
            ViewBag.user_id = new SelectList(db.user, "user_id", "username");
            return View();
        }

        // POST: critics/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HttpPostedFileBase critic_header, [Bind(Include = "critic_id,critic_header,critic_content,title,subtitle,critic_date_published,critic_date_reviewed,is_published,category_id,game_id,user_id")] critics critics)
        {
            String ct = "";
            //verify that the file is selected and not empty
            if (critic_header != null && critic_header.ContentLength > 0)
            {
                //getting the name of the file
                var fileName = Path.GetFileName(critic_header.FileName);

                //store file in the Books folder
                var path = Path.Combine(Server.MapPath("~/Images"), fileName);
                try
                {
                    critic_header.SaveAs(path);
                    ct = critic_header.FileName;
                }
                catch (Exception ex)
                {

                }
            }

            if (ModelState.IsValid)
            {
                critics.critic_header = ct;
                db.critics.Add(critics);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.game_id = new SelectList(db.games, "game_id", "name", critics.game_id);
            return View(critics);
        }

        // GET: critics/Edit/5

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            critics critics = db.critics.Find(id);
            if (critics == null)
            {
                return HttpNotFound();
            }
            ViewBag.game_id = new SelectList(db.games, "game_id", "name", critics.game_id);
            return View(critics);
        }

        // POST: critics/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(HttpPostedFileBase critic_header, [Bind(Include = "critic_id,critic_header,critic_content,title,subtitle,critic_date_published,critic_date_reviewed,is_published,category_id,game_id,user_id")] critics critics)
        {
            String ct = "";
            //verify that the file is selected and not empty
            if (critic_header != null && critic_header.ContentLength > 0)
            {
                //getting the name of the file
                var fileName = Path.GetFileName(critic_header.FileName);

                //store file in the Books folder
                var path = Path.Combine(Server.MapPath("~/Images"), fileName);
                try
                {
                    critic_header.SaveAs(path);
                    ct = critic_header.FileName;
                }
                catch (Exception ex)
                {

                }
            }
            if (ModelState.IsValid)
            {
                if (critics.critic_header != ct) {
                    critics.critic_header = ct;
                }
                db.Entry(critics).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.game_id = new SelectList(db.games, "game_id", "name", critics.game_id);
            return View(critics);
        }

        // GET: critics/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            critics critics = db.critics.Find(id);
            if (critics == null)
            {
                return HttpNotFound();
            }
            return View(critics);
        }

        // POST: critics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            critics critics = db.critics.Find(id);
            db.critics.Remove(critics);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [AllowAnonymous]
        public ActionResult ShowCritics() {
            
            return View(db.critics.ToList());
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JeuxCritique/WebApplication1/Views/critics/Create.cshtml
@model WebApplication1.critics
@{ 
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<h2>Create</h2>
@using (Html.BeginForm("Create", "critics", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
 @Html.AntiForgeryToken()

                <div class="form-horizontal">
        <h4>critics</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.title, "Titre de la critique", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div>@Html.LabelFor(model => model.critic_header, "image de la critique", htmlAttributes: new { @class = "control-label col-md-2" }))</div>
            <div class="col-md-10">
                <input type="file" name="critic_header" accept="image/*" />
                @Html.ValidationMessageFor(model => model.critic_header, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.subtitle, "Sous-titre de la critique", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.subtitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.subtitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.critic_content, "Contenu de votre critique", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.critic_content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.critic_content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.critic_date_published, "Date de publication de la critique", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.critic_date_published, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.critic_date_published, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.critic_date_reviewed, htmlAttributes: new { @class = "control-label col-md-2" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.is_published, "Etat de la publication", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.is_published)
                    @Html.ValidationMessageFor(model => model.is_published, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.game_id, "Jeu concerné", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("game_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.game_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Créer la critique" class="btn btn-default" />
            </div>
        </div>
    </div>
 
})


<div>
    @Html.ActionLink("Retourner à l'administration des critiques", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JeuxCritique/WebApplication1/Views/critics/Delete.cshtml
@model WebApplication1.critics

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>critics</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.critic_content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.critic_content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.subtitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.subtitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.critic_date_published)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.critic_date_published)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.critic_date_reviewed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.critic_date_reviewed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.is_published)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.is_published)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.games.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.games.name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

JeuxCritique/WebApplication1/Views/critics/Details.cshtml
@model WebApplication1.critics


@{
    ViewBag.Title = Model.title;
    JCModelEntities db = new JCModelEntities();
    var commentaire = db.comments.Where(x => x.id_critic == Model.critic_id);
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-lg-12">
    <article class="post-article" role="article">
        <header>
            @if (Request.IsAuthenticated)
            {
                <a href="/critics/Edit/@Model.critic_id" class="btn btn-default edit-post"><i class="icon-pencil icon-white"></i> Editer l'article</a>
                <a href="/critics/Delete/@Model.critic_id" class="btn btn-danger">Supprimer l'article</a><br /><br />
            }

            <div class="crop rel">
                @if (Model.critic_header != null)
                {
                    <img src="~/Images/@Model.critic_header" class="post-image" />
                }
                
                <div class="overlay">
                    <h1 class="title-article">


                        <br />
                        @Html.DisplayFor(model => model.title)
                        <br />
                        @Html.DisplayFor(model => model.subtitle)


                    </h1>

                </div>
            </div>

            <div>

                <br />

            </div>

            <div class="author">

                <div class="author-name-datehour">

                    Le @Html.DisplayFor(model => model.critic_date_published)

                    <br />

                    <br />

                </div>

            </div>

        </header>

        <div class="text-justify">

            @Html.Raw(Model.critic_content)



        </div>

        <div style="padding-bottom: 50px;">

        </div>

        <footer>

            <div class="tags row">
                <div class="col-lg-12">
                    <h1 class="text-center">
                        <a href="/Games/Details/@Model.games.game_id" target="_self">
                            @Html.DisplayFor(modelItem => Model.games.name)
                        </a>
                    </h1>
                    <br />
                </div>
                <div class="col-lg-2">
                    <img src="~/Images/@Model.games.jacket" class="image-elements" />
                </div>

                <div class="col-lg-10 row">
                    <div class="col-lg-4">
                        La norme européenne PEGI :
                        <br />
                        <a href="http://www.pegi.info/be_fr/index/id/837/" target="_blank"><i class="fa fa-info-circle" style="color:cornflowerblue"></i> Comprendre la norme PEGI</a>
                    </div>
                    <div class="col-lg-8">
                        @switch (int.Parse(Model.games.pegi))
                        {
                            case 3:
                                <a href="#" title="Avec cette classification, le contenu du jeu est considéré comme adapté à toutes les classes d'âge. Une certaine violence dans un contexte comique (par exemple les formes de violence présentes dans les dessins animés de type cartoon comme Bugs Bunny ou Tom & Jerry) est acceptable. L’enfant ne doit pas pouvoir associer le personnage à l'écran avec des personnages réels, ils doivent être totalement imaginaires. Le jeu ne doit pas comporter de sons ou d’images susceptibles d’effrayer ou de faire peur à de jeunes enfants.Le jeu ne doit faire entendre aucun langage grossier."><img src='~/Content/images/pegi/pegi-3.gif' /></a>;
                                break;
                            case 7:
                                <img src='~/Content/images/pegi/pegi-7.gif' />;
                                break;
                            case 12:
                                <img src='~/Content/images/pegi/pegi-12.gif' />;
                                break;
                            case 16:
                                <img src='~/Content/images/pegi/pegi-16.gif' />;
                                break;
                            case 18:
                                <img src='~/Content/images/pegi/pegi-18.gif' />;
                                break;
                            default:
                                <p>Aucune signalétique PEGI connue pour le moment.</p>;
                                break;
                        }
                </div>
                    <br />
                    <div class="col-lg-4">Description du jeu :  </div> 
                    <div class="col-lg-8">@Html.Raw(Model.games.description) </div>
                    <br />
                    <div class="col-lg-4">Fait par : </div> 
                    <div class="col-lg-8">
                        @Html.DisplayFor(model => model.games.developpers.name)
                    </div>
                    <br />
                    <div class="col-lg-4">Edité par : </div> 
                    <div class="col-lg-8">
                        @Html.DisplayFor(model => model.games.editors.name)
                    </div>
                <br />  
            </div>
            <div class="col-lg-12">
                <div style="float:left">
                    Noter le jeu
                    <div class="rating">
                        <input type="radio" name="starsrating" id="stars-rating-5" value="5">
                        <label for="stars-rating-5"><i class="fa fa-star"></i></label>
                        <input type="radio" name="starsrating" id="stars-rating-4" value="4">
                        <label for="stars-rating-4"><i class="fa fa-star"></i></label>
                        <input type="radio" name="starsrating" id="stars-rating-3" value="3">
                        <label for="stars-rating-3"><i class="fa fa-star"></i></label>
                        <input type="radio" name="starsrating" id="stars-rating-2" value="2">
                        <label for="stars-rating-2"><i class="fa fa-star"></i></label>
                        <input type="radio" name="starsrating" id="stars-rating-1" value="1">
                        <label for="stars-rating-1"><i class="fa fa-star"></i></label>
                    </div>
                </div>
</div>
</div>
    </footer>

</article>
    <div class="col-xs-12 article-commentaire">
        <span class="article-commentaire-title">
            Réagir ? 

        </span>
        <div class="col-lg-12">
            @if (Model.comments.Count == 0)
            {
                <p>Pas encore de commentaires</p>
            }
            else if (Model.comments.Count == 1)
            {
                <p> un commentaire</p>
            }
            else {
                <p> @Model.comments.Count commentaires </p>
            }
        </div>
        <div class="col-lg-12">
            @if (Model.comments.Count != 0)
            {
                foreach (var comm in Model.comments)
                {

                    <br /> @comm.comment
                }
            }

        </div>
        <div class="col-lg-12">
            @Model.comments.
        </div>
        <div id="form_comment">
                     
        </div>
    </div>
</div>

JeuxCritique/WebApplication1/Views/critics/Edit.cshtml
@model WebApplication1.critics

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Editer la critique sur le jeu @Model.games.name</h2>

@using (Html.BeginForm("Edit", "critics", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.critic_id)


        <div class="form-group">
            @Html.LabelFor(model => model.title, "Titre de la critique", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div>@Html.LabelFor(model => model.critic_header, "Image de la critique", htmlAttributes: new { @class = "control-label col-md-2" }))</div>
            <div class="col-md-10">
                <input type="file" name="critic_header" accept="image/*" />
                @Html.ValidationMessageFor(model => model.critic_header, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.subtitle, "Sous-titre", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.subtitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.subtitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.critic_content, "Contenu de votre critique", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.critic_content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.critic_content, "", new { @class = "text-danger" })
            </div>
        </div>
        
        s<div class="form-group">
            @Html.LabelFor(model => model.critic_date_published, "Date de la publication", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.critic_date_published, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.critic_date_published, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.critic_date_reviewed, "Date de modification",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.critic_date_reviewed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.critic_date_reviewed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.is_published, "Est-ce publié ?", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.is_published)
                    @Html.ValidationMessageFor(model => model.is_published, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.game_id, "game_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("game_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.game_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

JeuxCritique/WebApplication1/Views/critics/Index.cshtml
@model IEnumerable<WebApplication1.critics>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.critic_content)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.subtitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.critic_date_published)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.critic_date_reviewed)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.is_published)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.games.name)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @if (item.critic_content.Length > 50)
            {
                @item.critic_content.Substring(0, 50);
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.subtitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.critic_date_published)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.critic_date_reviewed)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.is_published)

        <td>
            @Html.DisplayFor(modelItem => item.games.name)
        </td>

        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.critic_id }) |
            @Html.ActionLink("Details", "Details", new { id=item.critic_id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.critic_id })
        </td>
    </tr>
}

</table>

JeuxCritique/WebApplication1/Views/critics/ShowCritics.cshtml
@{
    JCModelEntities db = new JCModelEntities();
    ViewBag.Title = "Toutes les critiques publiés";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1 class="text-center">La liste des critiques</h1>
<hr />
@{
    foreach (var item in db.critics)
    {
        if (item.is_published == true)
        {
            <div class="col-lg-12 col-sm-12">
                <div class="col-lg-3">
                    <a href="/Games/Details/@item.games.game_id">
                        <img src="~/Images/@item.games.jacket" class="image" />
                    </a>
                </div>
                <div class="col-lg-9">
                    <h2>@item.title</h2>
                </div>
                <div class="game-critique">
                    @if (item.critic_content.Length > 600)
                    {
                        @Html.Raw(item.critic_content.Substring(0, 600) + "...");
                    }
                    else {
                        @Html.Raw(item.critic_content);
                    }
                </div>
                <hr />
                <p class="text-center"><a href="/critics/Details/@item.critic_id" target="_self">Voir la suite de la critique de @item.games.name ?</a></p>
            </div>
            <hr />
        }
    }
}