JeuxCritique/WebApplication1/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1;

namespace WebApplication1.Controllers
{
    [Authorize]
    public class GamesController : Controller
    {
        private JCModelEntities db = new JCModelEntities();

        #region (methode de récupération de la dropdownlist pour la classification PEGI)

        private List<SelectListItem> norme_pegi() {
            List <SelectListItem> listItems = new List<SelectListItem>();
            listItems.Add(new SelectListItem
            {
                Text = "Pegi 3",
                Value = "3"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Pegi 7",
                Value = "7",
            });
            listItems.Add(new SelectListItem
            {
                Text = "Pegi 12",
                Value = "12"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Pegi 16",
                Value = "16"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Pegi 18",
                Value = "18"
            });
            return listItems;
        }
        #endregion

        // GET: Games
        [AllowAnonymous]
        public ActionResult Index()
        {
            var games = db.games.Include(g => g.developpers).Include(g => g.editors).Include(g=> g.games_consoles);
            return View(games.ToList());
        }

        // GET: Games/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            games games = db.games.Find(id);
            if (games == null)
            {
                return HttpNotFound();
            }
            return View(games);
        }

        // GET: Games/Create
        public ActionResult Create()
        {
            ViewBag.developper_id = new SelectList(db.developpers, "developper_id", "name");
            ViewBag.editor_id = new SelectList(db.editors, "editor_id", "name");
            ViewBag.Consoles = new SelectList(db.consoles, "console_id", "console_name");
            ViewBag.Pegi = norme_pegi();
            return View();
        }

        // POST: Games/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost,ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HttpPostedFileBase jacket, [Bind(Include = "game_id,name,jacket,pegi,description,gender_id,consoles_id,editor_id,developper_id")] games games)
        {
            String ct = "";
            //verify that the file is selected and not empty
            if (jacket != null && jacket.ContentLength > 0)
            {
                //getting the name of the file
                var fileName = Path.GetFileName(jacket.FileName);

                //store file in the Books folder
                var path = Path.Combine(Server.MapPath("~/Images"), fileName);
                try
                {
                    jacket.SaveAs(path);
                    ct = jacket.FileName;
                }
                catch (Exception ex)
                {
                    throw;
                }
            }
            if (ModelState.IsValid)
            {
                games.jacket = ct;
                db.games.Add(games);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.developper_id = new SelectList(db.developpers, "developper_id", "name", games.developper_id);
            ViewBag.editor_id = new SelectList(db.editors, "editor_id", "name", games.editor_id);
            return View(games);
        }

        // GET: Games/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.Pegi = norme_pegi();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            games games = db.games.Find(id);
            if (games == null)
            {
                return HttpNotFound();
            }
            ViewBag.developper_id = new SelectList(db.developpers, "developper_id", "name", games.developper_id);
            ViewBag.editor_id = new SelectList(db.editors, "editor_id", "name", games.editor_id);
            return View(games);
        }

        // POST: Games/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost,ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(HttpPostedFileBase jacket, [Bind(Include = "game_id,name,jacket,pegi,description,gender_id,consoles_id,editor_id,developper_id")] games games)
        {
            String ct = "";
            //verify that the file is selected and not empty
            if (jacket != null && jacket.ContentLength > 0)
            {
                //getting the name of the file
                var fileName = Path.GetFileName(jacket.FileName);

                //store file in the Books folder
                var path = Path.Combine(Server.MapPath("~/Images"), fileName);
                try
                {
                    jacket.SaveAs(path);
                    ct = jacket.FileName;
                }
                catch (Exception ex)
                {
                    throw;
                }
            }
            if (ModelState.IsValid)
            {
                if (games.jacket != ct && ct != "")
                {
                    games.jacket = ct;
                }
                db.Entry(games).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.developper_id = new SelectList(db.developpers, "developper_id", "name", games.developper_id);
            ViewBag.editor_id = new SelectList(db.editors, "editor_id", "name", games.editor_id);
            return View(games);
        }
        [Authorize]
        public ActionResult Critics(int? id)
        {
            if (id == null) {
                return RedirectToAction("Index");
            }
            ViewBag.game = db.games;
            return View();
        }

        // POST: critics/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Critics([Bind(Include = "critic_id,critic_content,critic_header,title,subtitle,critic_date_published,critic_date_reviewed,is_published,category_id,game_id,user_id")] critics critics)
        {
  

            if (ModelState.IsValid)
            {
                db.critics.Add(critics);
                db.SaveChanges();
                ViewBag.Message = "Critique crée, merci !";
                return RedirectToAction("Index");
            }

            ViewBag.game_id = new SelectList(db.games, "game_id", "name", critics.game_id);
            return View(critics);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JeuxCritique/WebApplication1/Controllers/criticsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1;

namespace WebApplication1.Controllers
{
    [Authorize]
    public class criticsController : Controller
    {
        private JCModelEntities db = new JCModelEntities();

        // GET: critics
        [AllowAnonymous]
        public ActionResult Index()
        {
            var critics = db.critics.Include(c => c.games);
            return View(critics.ToList());
        }

        // GET: critics/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            critics critics = db.critics.Find(id);
            //comments comments = db.comments.Where(g => g.id_critic == id);
            if (critics == null)
            {
                return HttpNotFound();
            }
            return View(critics);
        }

        // GET: critics/Create
        public ActionResult Create()
        {
            ViewBag.category_id = new SelectList(db.category, "id_category", "category_name");
            ViewBag.game_id = new SelectList(db.games, "game_id", "name");
            ViewBag.user_id = new SelectList(db.user, "user_id", "username");
            return View();
        }

        // POST: critics/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HttpPostedFileBase critic_header, [Bind(Include = "critic_id,critic_header,critic_content,title,subtitle,critic_date_published,critic_date_reviewed,is_published,category_id,game_id,user_id")] critics critics)
        {
            String ct = "";
            //verify that the file is selected and not empty
            if (critic_header != null && critic_header.ContentLength > 0)
            {
                //getting the name of the file
                var fileName = Path.GetFileName(critic_header.FileName);

                //store file in the Books folder
                var path = Path.Combine(Server.MapPath("~/Images"), fileName);
                try
                {
                    critic_header.SaveAs(path);
                    ct = critic_header.FileName;
                }
                catch (Exception ex)
                {

                }
            }

            if (ModelState.IsValid)
            {
                critics.critic_header = ct;
                db.critics.Add(critics);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.game_id = new SelectList(db.games, "game_id", "name", critics.game_id);
            return View(critics);
        }

        // GET: critics/Edit/5

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            critics critics = db.critics.Find(id);
            if (critics == null)
            {
                return HttpNotFound();
            }
            ViewBag.game_id = new SelectList(db.games, "game_id", "name", critics.game_id);
            return View(critics);
        }

        // POST: critics/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(HttpPostedFileBase critic_header, [Bind(Include = "critic_id,critic_header,critic_content,title,subtitle,critic_date_published,critic_date_reviewed,is_published,category_id,game_id,user_id")] critics critics)
        {
            String ct = "";
            //verify that the file is selected and not empty
            if (critic_header != null && critic_header.ContentLength > 0)
            {
                //getting the name of the file
                var fileName = Path.GetFileName(critic_header.FileName);

                //store file in the Books folder
                var path = Path.Combine(Server.MapPath("~/Images"), fileName);
                try
                {
                    critic_header.SaveAs(path);
                    ct = critic_header.FileName;
                }
                catch (Exception ex)
                {

                }
            }
            if (ModelState.IsValid)
            {
                if (critics.critic_header != ct) {
                    critics.critic_header = ct;
                }
                db.Entry(critics).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.game_id = new SelectList(db.games, "game_id", "name", critics.game_id);
            return View(critics);
        }

        // GET: critics/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            critics critics = db.critics.Find(id);
            if (critics == null)
            {
                return HttpNotFound();
            }
            return View(critics);
        }

        // POST: critics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            critics critics = db.critics.Find(id);
            db.critics.Remove(critics);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [AllowAnonymous]
        public ActionResult ShowCritics() {
            
            return View(db.critics.ToList());
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JeuxCritique/WebApplication1/Views/Games/Create.cshtml
@model WebApplication1.games

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    List<SelectListItem> listItems = ViewBag.Pegi;
}

<h2 class="text-center">Créer un nouveau jeu dans la base de données</h2>

@using (Html.BeginForm("Create", "Games", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.name, "Titre du jeu", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.jacket, "image de la critique", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                <input type="file" name="jacket" accept="image/*" />
                @Html.ValidationMessageFor(model => model.jacket, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.pegi, "La norme PEGI pour le jeu", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.DropDownListFor(model => model.pegi, listItems, htmlAttributes: new { @value = "Text",@class = "form-control" })
                @Html.ValidationMessageFor(model => model.pegi, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.description,"Courte description du jeu à enregistrer", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gender_id, "Genre du jeu", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.gender_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.gender_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.consoles_id, "Sur quelle console est-elle disponible ?", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">

                @Html.DropDownList("consoles", null,  htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.consoles_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.editor_id, "Editeur du jeu", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.DropDownList("editor_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.editor_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.developper_id, "Developpeur du jeu", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.DropDownList("developper_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.developper_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <input type="submit" value="Create" class="btn btn-default text-center" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

JeuxCritique/WebApplication1/Views/Games/Critics.cshtml
@model WebApplication1.critics

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <h2 class="text-center">Vous créez actuellement une critique pour le jeu @ViewBag.game_id</h2>
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.title, "Titre de la critique", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.subtitle, "Sous-titre de la critique", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.subtitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.subtitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.critic_content, "Contenu de votre critique", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.critic_content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.critic_content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.critic_date_reviewed, new { @Value = DateTime.Now })
            @Html.HiddenFor(model => model.critic_date_published, new { @Value = DateTime.Now })
            @Html.HiddenFor(model => model.is_published, new { @Value = false }) 
            @Html.HiddenFor(model => model.game_id, new { @Value = ViewBag.game })
            @Html.HiddenFor(model => model.critic_header, new { @Value = "" })

        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Créer la critique" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JeuxCritique/WebApplication1/Views/Games/Details.cshtml
@model WebApplication1.games

@{
    ViewBag.Title = "Details";
    JCModelEntities db = new JCModelEntities();
    int count = 0;
    foreach (var critic in db.critics)
    {
        if (Model.game_id == critic.game_id && critic.is_published == true)
        {

            count++;
        }
    }
}

<div class="row">

    @if (Request.IsAuthenticated)
            {
        <div style="position:relative;">
            <div style="position:absolute; z-index:999; right:0;">
                <a href="/Games/Edit/@Html.DisplayFor(modelItem => Model.game_id)" class="btn btn-default">Modifier le jeu</a>
            </div>
        </div>
    }

    <div class="col-lg-12">
        <h1 class="text-center">
            <a href="/Games/Details/@Model.game_id" target="_self">
                @Html.DisplayFor(modelItem => Model.name)
            </a>
        </h1>
        <br />
    </div>
    <div class="col-lg-2">
        <img src="~/Images/@Model.jacket" class="image-elements" />
    </div>

    <div class="col-lg-10 row">
        <div class="col-lg-3">
            La norme européenne PEGI :
            <br />
            <a href="http://www.pegi.info/be_fr/index/id/837/" target="_blank"><i class="fa fa-info-circle" style="color:cornflowerblue"></i> Comprendre la norme PEGI</a>
        </div>
        <div class="col-lg-9">
            @switch (int.Parse(Model.pegi))
            {
                case 3:
                    <a href="#" title="Avec cette classification, le contenu du jeu est considéré comme adapté à toutes les classes d'âge. Une certaine violence dans un contexte comique (par exemple les formes de violence présentes dans les dessins animés de type cartoon comme Bugs Bunny ou Tom & Jerry) est acceptable. L’enfant ne doit pas pouvoir associer le personnage à l'écran avec des personnages réels, ils doivent être totalement imaginaires. Le jeu ne doit pas comporter de sons ou d’images susceptibles d’effrayer ou de faire peur à de jeunes enfants.Le jeu ne doit faire entendre aucun langage grossier."><img src='~/Content/images/pegi/pegi-3.gif' /></a>;
                    break;
                case 7:
                    <img src='~/Content/images/pegi/pegi-7.gif' />;
                    break;
                case 12:
                    <img src='~/Content/images/pegi/pegi-12.gif' />;
                    break;
                case 16:
                    <img src='~/Content/images/pegi/pegi-16.gif' />;
                    break;
                case 18:
                    <img src='~/Content/images/pegi/pegi-18.gif' />;
                    break;
                default:
                    <p>Aucune signalétique PEGI connue pour le moment.</p>;
                    break;
            }


        </div>
        <br />
        <div class="col-lg-3">Description du jeu :  </div> <div class="col-lg-9">@Html.Raw(Model.description) </div>
        <br />
        <div class="col-lg-3">Fait par : </div> <div class="col-lg-9">
            @Html.DisplayFor(modelItem => Model.developpers.name)
        </div>
        <br />
        <div class="col-lg-3">Edité par : </div> <div class="col-lg-9">
            @Html.DisplayFor(modelItem => Model.editors.name)
        </div>
        <br />

    </div>
    <div class="col-lg-12">
        <div style="float:left">
            Noter le jeu
            <div class="rating">
                <input type="radio" name="starsrating" id="stars-rating-5" value="5">
                <label for="stars-rating-5"><i class="fa fa-star"></i></label>
                <input type="radio" name="starsrating" id="stars-rating-4" value="4">
                <label for="stars-rating-4"><i class="fa fa-star"></i></label>
                <input type="radio" name="starsrating" id="stars-rating-3" value="3">
                <label for="stars-rating-3"><i class="fa fa-star"></i></label>
                <input type="radio" name="starsrating" id="stars-rating-2" value="2">
                <label for="stars-rating-2"><i class="fa fa-star"></i></label>
                <input type="radio" name="starsrating" id="stars-rating-1" value="1">
                <label for="stars-rating-1"><i class="fa fa-star"></i></label>
            </div>
        </div>
      
    </div>
    
</div>
<hr />
    @if (count != 0)
    {   
        <h2 class="text-center">
        Les critiques associés au jeu (
            @if (count == 1)
                {
            @Html.Raw("une critique");
                }
                else {
            @Html.Raw(count + "critiques");
                } )
        </h2>
        <div class="col-lg-12 row">


        
        @{
            foreach (var item in Model.critics)
            {
                if (item.is_published == true)
                {
                    <div class="col-lg-12 col-sm-12">
                        <div class="col-lg-12">
                            <h2>@item.title</h2>
                        </div>
                        <div class="game-critique">
                            @if (item.critic_content.Length > 600)
                            {
                                @Html.Raw(item.critic_content.Substring(0, 600) + "...");
                            }
                            else {
                                @Html.Raw(item.critic_content);
                            }
                        </div>
                        <hr />
                        <p class="text-center"><a href="/critics/Details/@item.critic_id" target="_self">Voir la suite de la critique de @item.games.name ?</a></p>
                    </div>
                    <hr />
                }
            }
        }
    </div>
            }
            else {
                <div class="col-lg-12">Pas encore de critiques pour ce jeu.</div>
            }
<div class="col-lg-12 controls">
    <a href="/Games/Critics/@Model.game_id" class="btn btn-lg btn-primary btn-block" type="submit">Ecrire une critique ?</a>

</div>

JeuxCritique/WebApplication1/Views/Games/Edit.cshtml
@model WebApplication1.games

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    List<SelectListItem> listItems = ViewBag.Pegi;
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Games", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>games</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.game_id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.pegi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.pegi, listItems, htmlAttributes: new { @value = "Text", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.pegi, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.jacket, "image de la critique", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="jacket" accept="image/*" />
                @Html.ValidationMessageFor(model => model.jacket, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gender_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.gender_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.gender_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.consoles_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.consoles_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.consoles_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.editor_id, "editor_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("editor_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.editor_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.developper_id, "developper_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("developper_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.developper_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>